### ISSUE TITLE
barvanje zemljevida

### ISSUE THREAD

**Issue by anjazavrl** [anjazavrl/APPR-2014-15#5]
Ne vem kaj je narobe pri kodi v mapi Vizualizacija, saj mi zemljevida sploh ne pobarva. 
Je kaj narobe, ker so imena držav v Evropi malo bolj skupaj?

Nikakor mi ne uspe povečati slike zemljevidu v poročilu. Sem poskusila s parametorm `scale` in `width`, vendar se mi potem vse zamakne.

**Comment by jaanos** [comment]
Barve poskušaš dobiti z imenskimi indeksi, a jih vektor `barve` nima. Takoj za tem, ko ga definiraš, jih lahko nastaviš:
```R
names(barve) <- names(t)
```

Zemljevid naj bo čitljiv, tako da ni najlepše, če so imena preveč zbita skupaj. Lahko jih skrajšaš ali celo izpustiš; lahko pa npr. narediš črte od imen do države. Koordinat držav ti ni potrebno uvažati, saj jih lahko dobiš že iz zemljevida samega (poleg tega imaš napačne podatke za Italijo in Avstrijo, zato ti ne izpiše imen). Lahko narediš torej nekaj takega:
```R
# pripravimo koordinate držav
koord.orig <- coordinates(svet[match(names(t), svet$name_long),])
rownames(koord.orig) <- names(t)
# spreminjali bomo koordinate imen
koord.ime <- koord.orig
imena <- names(t)
# pripravimo vektor imen
names(imena) <- names(t)
# pripravimo vektor pozicij
pos <- rep(1, length(t))
names(pos) <- names(t)
# pripravimo vektor odmikov
offset <- rep(0, length(t))
names(offset) <- names(t)
# povemo, katere države bomo pokazali s črto
zamaknjene <- c("Austria", "France", "Italy", "United Kingdom")
offset[zamaknjene] <- 0.5

# priredimo pozicije imen držav
koord.ime["Austria",1] <- koord.ime["Austria",1] + 10 # premik po osi x
koord.ime["France",1] <- koord.ime["France",1] - 7 # premik po osi x
koord.ime["United Kingdom",2] <- koord.ime["United Kingdom",2] + 8 # premik po osi y
koord.ime["Italy",] <- koord.ime["Italy",] + c(6, -8) # premik po obeh oseh

# povemo, kje glede na točko naj bo prikazano ime
pos["Austria"] <- 4 # desno
pos["France"] <- 2 # levo
pos["Italy"] <- 1 # spodaj
pos["United Kingdom"] <- 3 # zgoraj

# priredimo imena
imena["United Kingdom"] <- "UK"

# izpišemo imena
text(koord.ime, labels = imena, col = "black", cex = 0.6, pos = pos, offset = offset)

# narišemo črte
for (drzava in zamaknjene) {
  lines(c(koord.ime[drzava,1], koord.orig[drzava,1]),
        c(koord.ime[drzava,2], koord.orig[drzava,2]))
}
```
Lahko bi tudi posebej narisala zemljevid Evrope, kjer bi bila imena lepše prikazana.

Da bi povečala sliko v poročilu, lahko narediš nekaj takega:
```LaTeX
\makebox[\textwidth][c]{
\includegraphics[width=1.5\textwidth]{../slike/Zmage_po_drzavah.pdf}
}
```

**Comment by anjazavrl** [comment]
Najlepša hvala za pomoč. Sem tudi sama razmišljala že o teh črtah in tudi o tem, da bi narisala Evropo posebej, vendar nisem točno vedela kako.

**Comment by jaanos** [comment]
Zemljevid sveta, ki ga uporabljaš, ima podatek o celini, na kateri je država, tako da lahko zemljevid Evrope dobiš z
```R
evropa <- svet[svet$continent == "Europe",]
```
Ta zemljevid sicer vsebuje celotno Rusijo in Francosko Gvajano (kot del Francije), tako da bo potrebno pri izrisu podati še meje, npr.:
```R
plot(evropa, xlim = c(-20, 20), ylim = c(33, 73))
```
