### ISSUE TITLE
XML

### ISSUE THREAD

**Issue by anjazavrl** [anjazavrl/APPR-2014-15#6]
Pri klicu tabele s pomočjo XML mi pokaže nek error, nevem kaj bi lahko bilo, saj mi je včasih delalo. Morda kaj s spletno stranjo, saj kode nisem spreminjala?

**Comment by jaanos** [comment]
Spletna stran se je očitno spremenila - sedaj imaš iskane podatke v peti namesto v šesti tabeli.

Meni sicer ni hotelo odpreti spletne strani (kriva je posodobitev R-ja). V izogib težavam svetujem, da vključiš knjižnico `httr` (morda jo boš morala še namestiti), `doc.konstruktorske.zmage` pa dobiš kot
```R
doc.konstruktorske.zmage <- htmlTreeParse(GET(url.konstruktorske.zmage),encoding = "UTF-8", useInternalNodes=TRUE)
```
(dodana je funkcija `GET` okoli URL-ja).
